<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KappaCopy.Core\KappaCopy.Core.csproj" />
    <ProjectReference Include="..\KappaCopy.Engine\KappaCopy.Engine.csproj" />
  </ItemGroup>
</Project>
